name: Run Puppeteer Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت یک بار
  workflow_dispatch:  # برای اجرای دستی

concurrency:
  group: bot-runner
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install p7zip
        run: sudo apt update && sudo apt install -y p7zip-full

      - name: Extract affect.7z into input
        run: |
          7z x affect.7z -oinput -p"${{ secrets.ZIP_PASSWORD }}" -y

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        working-directory: ./input
        run: bun install

      - name: Install Chromium
        working-directory: ./input
        run: |
          sudo apt update
          sudo apt install -y chromium

      - name: Run index.js with Bun
        working-directory: ./input
        run: bun index.js
        env:
          NODE_ENV: production
