name: Run Puppeteer Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # هر ۵ دقیقه یک بار برای تست
  workflow_dispatch:
    inputs:
      zip_password:
        description: 'رمز عبور فایل affect.7z'
        required: false
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask password
        run: echo "::add-mask::${{ secrets.ZIP_PASSWORD || github.event.inputs.zip_password }}"

      - name: Install p7zip
        run: sudo apt update > /dev/null 2>&1 && sudo apt install -y p7zip-full > /dev/null 2>&1

      - name: Extract affect.7z into input
        run: |
          7z x affect.7z -oinput -p"${{ secrets.ZIP_PASSWORD || github.event.inputs.zip_password }}" -y > /dev/null 2>&1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        working-directory: ./input
        run: bun install > /dev/null 2>&1

      - name: Install Chromium
        working-directory: ./input
        run: |
          sudo apt update > /dev/null 2>&1
          sudo apt install -y chromium > /dev/null 2>&1

      - name: Run index.js with Bun
        working-directory: ./input
        run: bun index.js > /dev/null 2>&1
        env:
          NODE_ENV: production
